### ISSUE TITLE
Problem z uvozom

### ISSUE THREAD

**Issue by SamoFMF** [Ahcinn13/vanesa#1]
Na vajah smo govorili o uvozo s te spletne strani http://www.tennisscores-stats.com/headtohead.php

Za par igralcev bi radi uvozili tabelo 'Head to Head matches'.

**Comment by SamoFMF** [comment]
Bi bilo možno to narediti še za http://www.tennisscores-stats.com/tournament-description.php ? Potrebovali pa bi tabelo pod 'Tournament Statistics'.

Sem poizkušal sam nekoliko prirediti kodo, da bi delovalo, pa mi ni uspelo.

Hvala za pomoč.

**Comment by jaanos** [comment]
Sem dodal funkcijo kar zraven #2.
