### ISSUE TITLE
Relacije

### ISSUE THREAD

**Issue by SamoFMF** [Ahcinn13/vanesa#3]
Pozdravljeni.

Imamo probleme z ustvarjanjem relacij. Ne znamo ustvariti tabel, ki bi jih vnesli kot relacije in tudi koda pri https://github.com/BraMira/Mirjam-Spela/issues/5 nam ni dovolj pomagala, da bi zadevo usposobili.

Tako da bi prosil, če bi lahko pokazali na našem primeru, naprimer relacija 'has_player', ki povezuje tabeli 'statistics' in 'player'.

Upam, da imamo tabelo za relacijo sicer pravilno nastavljeno.

Hvala za pomoč!

**Comment by jaanos** [comment]
`STATISTICS` je na ER diagramu šibka entiteta - ustrezala bo torej tabeli, ki bo imela referenco kot del primarnega ključa:

``` SQL
CREATE TABLE statistics (
  won INTEGER NOT NULL,
  loss INTEGER NOT NULL,
  perc_spw NUMERIC,
  aces INTEGER,
  dfs INTEGER,
  perc_rpw NUMERIC,
  perc_bpoc NUMERIC,
  tiebreak_w INTEGER,
  tiebreak_l INTEGER,
  season INTEGER,
  player_id INTEGER REFERENCES player(player_id),
  PRIMARY KEY (player_id, season)
);
```

Lahko bi sicer imeli stolpec tipa `SERIAL` kot glavni ključ in bi namesto trenutnega `PRIMARY KEY` uporabili `UNIQUE`, a glede na to, da nimate referenc na tabelo `statistics`, to niti ni potrebno.

**Comment by SamoFMF** [comment]
Hvala, vendar sem imel v mislih nekaj v smislu:

V naši `head2head` tabeli imamo med drugim stolpca `tournament` in `year`, ki se skupaj navezujeta na tabelo `TOURNAMENT`, kjer pa smo vsakemu turnirju (torej paru `tournament`, `year`) dali `id`, ki je `serial`. Kako bi sedaj te `id`-je prenesli v tabelo `head2head`, da bi namesto `tournament` in `year` imeli samo `tourn_id` in bi le-to lahko referencali potem na `TOURNAMENT`?

**Comment by jaanos** [comment]
Ob predpostavki, da v tabeli `head2head` namesto stolpcev `year` in `tournament` na konec stolpec `tournament`, ki je referenca na `tournament(tourn_id)`, bi šlo takole:

``` R
con <- src_postgres(dbname = db, host = host, user = user, password = password)
tbl.tournament <- tbl(con, "tournament")
data.h2h <- head2head %>%
  inner_join(tbl.tournament %>%
               select(tournament = tourn_id, Tournament = name, Year = year),
             copy = TRUE) %>% select(-Year, -Tournament)
dbWriteTable(conn, name='head2head', data.h2h, append=T, row.names=F)
```

Če vrstni red stolpcev ne bi bil pravi, lahko v drugem `select` namesto izpuščanja stolpcev poskrbite, da izberete stolpce v pravem vrstnem redu. Parameter `copy = TRUE` pri `inner_join` poskrbi, da se tabela `tournament` iz baze (ker je precej velika, so tukaj izbrani samo potrebni stolpci) takoj prenese in se join izvede lokalno (ker je razpredelnica `head2head` zaenkrat na voljo samo lokalno).
Potem se lahko dobljena razpredelnica zapiše z `dbWriteTable`.

Svetujem, da ID-je daste tudi igralcem. Seveda bo potem treba tudi za tabelo `head2head` imena igralcev nadomestiti z ID-ji. Glede na to, da boste to morali narediti večkrat (samo tukaj dvakrat), bo najbolje, če si takoj potegnete tabelo igalcev iz baze (ta ni prevelika, potrebujete pa samo ime in ID) ter potem joine izvajate lokalno (torej parameter `copy = TRUE` ni potreben, če je tudi druga razpredelnica na voljo lokalno).
